GRANT USAGE ON SCHEMA public TO cm_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cm_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cm_runtime;
REVOKE UPDATE, DELETE, TRUNCATE ON audit FROM cm_runtime;
REVOKE DELETE, TRUNCATE ON records, record_links FROM cm_runtime;
REVOKE UPDATE ON record_links FROM cm_runtime;
REVOKE ALL ON _sqlx_migrations FROM cm_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE cm_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cm_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE cm_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cm_runtime;
